anime.js and MathComponent
prometium/IKBO-02-16-Coursework-JS pull request #13
Opened 2019-12-23 18:57 UTC by narcologer

2019-12-23 19:46 UTC, rugged-bl commented on src/routes/NarcologerPage/NarcologerPage.js
> +        <script src="src/components/MathComponent"></script>
Думаю, подключать компонент через `script` здесь явно излишне, isn't it? @prometium

2019-12-23 19:52 UTC, prometium requested changes
Very poor code quality. Please, use React ref (https://ru.reactjs.org/docs/hooks-reference.html#useref) to access DOM node in React component.
`<script src="src/components/MathComponent"></script>` - use import instead.
The component must not contain any scripts!
Side effects must be executed in `useEffect` hook.

2019-12-23 19:55 UTC, prometium commented on src/routes/NarcologerPage/NarcologerPage.js
> +        <script src="src/components/MathComponent"></script>
Of course!

2019-12-23 20:07 UTC, prometium commented
Here is the correct use of ref:

```javascript
...
const linesEl = React.useRef();

useEffect(() => {
    ...
    var lineDrawing = anime({
      targets: linesEl.current.childNodes,
     ...
  });

...
<g ref={linesEl}>
...
```

2019-12-23 20:12 UTC, prometium commented
Use ref, remove all `<script />` and we will gladly accept your PR. If possible, install the eslint plugin (for VS Code) and remove unnecessary code.

2019-12-24 08:06 UTC, Wo1kowsky commented
BRUH

2019-12-24 10:26 UTC, prometium approved these changes
Nice fix and addition!

2019-12-24 10:30 UTC, prometium requested changes

2019-12-24 10:30 UTC, prometium commented on src/routes/NarcologerPage/NarcologerPage.css
> +  }
Here is another issue. Because of the use of global style, the background turns black on all pages. Use css class instead for your root element.

2019-12-24 12:03 UTC, prometium approved these changes
Now, it's all right!

2019-12-24 12:03 UTC, merged